<?php
namespace App\Http\Controllers;
use App\Exports\UsersExport;
use App\Imports\UsersImport;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use function GuzzleHttp\Psr7\copy_to_string;

class UserController  extends Controller
{
    /**
     * @return \Illuminate\Support\Collection
     */
    public function importExportView()
    {
        return view('import');
    }
    /**
     * @return \Illuminate\Support\Collection
     */

    public function search($query)
{
    $users= User::where('nom','like',"%$query%")
        ->orWhere('prenom','like',"%$query%")
        ->orWhere('email','like',"%$query%")
        ->get();

    //return View
    return $users;
}
    public function export()
    {
        return Excel::download(new UsersExport, 'users.xlsx');
    }
    /**
     * @return \Illuminate\Support\Collection
     */
    public function import(Request $request)
    {
        Excel::import(new UsersImport,$request->file('file'));

        return back();
    }

    public function supp($id)
    {
        $res=User::where('id',$id)->delete();


        return $res;

             }



    public function Ajout(Request $request)
    {
        $all = $request->all();
        $User = new User();


        $User->nom = $all['nom'];
        $User->prenom = $all['prenom'];
        $User->email = $all['email'];

        $User->password = \Hash::make($all['password']);
        $User->role = $all['Role'];


        $User->id_domaine= $all['code_domaine'];
        $User->id_specialite= $all['code_specialite'];
        $User->suppression=$all['suppression'];
        $User->dateSuppression=$all['dateSuppression'];
        $use=User::where('email','like',"$User->email")->get();
        $userr = User::where('email','like',"$User->email")->onlyTrashed()
            ->update(['deleted_at' => null,'nom'=>$all['nom'],'prenom' =>$all['prenom'],'password' => \Hash::make($all['password']),
                'Role' => $all['Role'],'id_domaine' => $all['code_domaine'],'id_specialite' =>$all['code_specialite'],
                'suppression'=>$all['suppression'],'dateSuppression'=>$all['dateSuppression']]);


        if(count($use)==0 && !$userr   ) {
          $User->save();
          return 1;
        }
        else if(count($use)!=0  )
        {
            return 0 ;
        }

        return 3;



       }
       public function suppression_auto()
      {$today=date('Y-m-d');

      return User::where('dateSuppression','<=',"$today")->delete(); ;



         }

    public function liste()
    {
        return User::all();
        //return User::withTrashed()->get();
    }

    public function changepassword(Request $request)
    {
       /* $data = $request->all();
        $user = Auth::guard('api')->user();
   
        //Changing the password only if is different of null
        if( isset($data['oldPassword']) && !empty($data['oldPassword']) && $data['oldPassword'] !== "" && $data['oldPassword'] !=='undefined') {
            //checking the old password first
            $check  = Auth::guard('web')->attempt([
                'prenom' => $user->prenom,
                'password' => $data['oldPassword']
            ]);
            if($check && isset($data['newPassword']) && !empty($data['newPassword']) && $data['newPassword'] !== "" && $data['newPassword'] !=='undefined') {
                $user->password = bcrypt($data['newPassword']);
                $user->isFirstTime = false; //variable created by me to know if is the dummy password or generated by user.
                $user->token()->revoke();
                $token = $user->createToken('newToken')->accessToken;
   
                //Changing the type
                $user->save();
   
                return json_encode(array('token' => $token)); //sending the new token
            }
            else {
                return "Wrong password information";
            }
        }
        return "Wrong password information";
    */
  
   
    
    

    
       /*f(!(Hash::check($request->get('current_password'), Auth::user()->password))){
            return response()->json([
                
                'message' => 'your current password does not match'
              ]);
        }
        if(strcmp($request->get('current_password'), $request->get('new_password'))==0){
            return response()->json([
                
                'message' => 'your current password does not be the same with new passsword'
              ]);
        }
        $request->validate([
            'current_password' =>'required',
            'new_password' =>'required',

        ]);
        $user = Auth::user();
        $user->password = bcrypt($request->get('new_password'));
        $user->save();
        return response()->json([
               
            'message' => 'password change'
          ]);*/

       //return  $request->all();
       /*$user=User::find(Auth::user()->id);
       if($user){
        if(Hash::check($request['oldpassword'],$user->password))
        {
            
            $user->password= Hash::make($request->password);
            $user->save();
            return response()->json([
               
                'message' => 'password change'
              ]);
        }
        else {
            return response()->json([
                
                'message' => 'Erreur'
              ]);
        }
    }*/

    $data = $request->all();

        if(!\Hash::check($data['old_password'], auth()->user()->password)){

             return back()->with('error','You have entered wrong password');

        }else{

            $user = Auth::user();
            $user->password = bcrypt($request->get('new_password'));
            $user->save();
            return response()->json([
                   
                'message' => 'password change'
              ]);

        }
    }





}
?>
